name: CI

on:
  push:
    branches:
      - main

jobs:
  go-test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      - run: go test ./...
      - run: go build ./...

  bun-test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - run: cd client && bun install
      - run: cd client && bun test
      - run: cd client && bun run build
